version: '3.4'
services:
 mysql:
   hostname: mysql
   image: mysql:5.7
   restart: always
   logging:
     driver: none
   environment:
     MYSQL_DATABASE: 'ticket'
     MYSQL_USER: 'admin'
     MYSQL_PASSWORD: 'P@ssw0rd'
     MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
   ports:
     - '3306:3306'

 discovery-server:
   hostname: eureka
   build:
     context: eurekaserver
     dockerfile: Dockerfile
   ports:
     - "8761:8761"
   depends_on:
     - mysql

 client:
   hostname: client
   build:
     context: eurekaclient
     dockerfile: Dockerfile
   ports:
     - "8082:8082"
   depends_on:
     - discovery-server
 